create table if not exists public.course_libraries (
  user_id uuid primary key references auth.users(id) on delete cascade,
  library jsonb not null default '{"progress":{},"favorites":[],"completedResources":[],"studyPlans":{},"lastOpenedResource":null}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.course_libraries enable row level security;

create policy "Users can read their own course library"
on public.course_libraries for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create their own course library"
on public.course_libraries for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own course library"
on public.course_libraries for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  message text not null check (char_length(message) between 10 and 4000),
  email text check (email is null or char_length(email) <= 320),
  page_url text check (page_url is null or char_length(page_url) <= 2000),
  created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;

create policy "Anyone can submit beta feedback"
on public.feedback for insert
to anon, authenticated
with check (char_length(message) between 10 and 4000);
