create table if not exists public.course_libraries (
  user_id uuid primary key references auth.users(id) on delete cascade,
  library jsonb not null default '{"progress":{},"favorites":[],"completedResources":[],"studyPlans":{},"lastOpenedResource":null}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.course_libraries enable row level security;

drop policy if exists "Users can read their own course library" on public.course_libraries;
create policy "Users can read their own course library"
on public.course_libraries for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can create their own course library" on public.course_libraries;
create policy "Users can create their own course library"
on public.course_libraries for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own course library" on public.course_libraries;
create policy "Users can update their own course library"
on public.course_libraries for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create or replace function public.save_course_library(
  p_expected_updated_at timestamptz,
  p_library jsonb
)
returns table (
  result_status text,
  result_updated_at timestamptz,
  result_library jsonb
)
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_saved_at timestamptz := clock_timestamp();
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if p_expected_updated_at is null then
    insert into public.course_libraries (user_id, library, updated_at)
    values (v_user_id, p_library, v_saved_at)
    on conflict (user_id) do nothing;

    if found then
      return query select 'saved'::text, v_saved_at, p_library;
      return;
    end if;
  else
    update public.course_libraries
    set library = p_library, updated_at = v_saved_at
    where user_id = v_user_id and updated_at = p_expected_updated_at;

    if found then
      return query select 'saved'::text, v_saved_at, p_library;
      return;
    end if;
  end if;

  return query
  select 'conflict'::text, course_libraries.updated_at, course_libraries.library
  from public.course_libraries
  where course_libraries.user_id = v_user_id;
end;
$$;

revoke all on function public.save_course_library(timestamptz, jsonb) from public;
grant execute on function public.save_course_library(timestamptz, jsonb) to authenticated;

create or replace function public.get_course_favorite_counts()
returns table (
  course_id text,
  favorite_count bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select favorite.course_id, count(*)::bigint
  from public.course_libraries
  cross join lateral jsonb_array_elements_text(
    case
      when jsonb_typeof(course_libraries.library -> 'favorites') = 'array'
        then course_libraries.library -> 'favorites'
      else '[]'::jsonb
    end
  ) as favorite(course_id)
  group by favorite.course_id;
$$;

revoke all on function public.get_course_favorite_counts() from public;
grant execute on function public.get_course_favorite_counts() to anon, authenticated;

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  message text not null check (char_length(message) between 10 and 4000),
  email text check (email is null or char_length(email) <= 320),
  page_url text check (page_url is null or char_length(page_url) <= 2000),
  created_at timestamptz not null default now()
);

alter table public.feedback add column if not exists issue_type text;
alter table public.feedback add column if not exists status text not null default 'new';
alter table public.feedback add column if not exists language text;
alter table public.feedback add column if not exists viewport text;
alter table public.feedback add column if not exists app_version text;

alter table public.feedback drop constraint if exists feedback_issue_type_check;
alter table public.feedback add constraint feedback_issue_type_check check (issue_type is null or issue_type in ('broken-link', 'course-data', 'curriculum-data', 'missing-course', 'study-plan', 'account-sync', 'mobile-accessibility', 'translation', 'account-deletion', 'other'));
alter table public.feedback drop constraint if exists feedback_status_check;
alter table public.feedback add constraint feedback_status_check check (status in ('new', 'reviewing', 'resolved', 'closed'));
alter table public.feedback drop constraint if exists feedback_language_check;
alter table public.feedback add constraint feedback_language_check check (language is null or language in ('en', 'zh'));
alter table public.feedback drop constraint if exists feedback_viewport_check;
alter table public.feedback add constraint feedback_viewport_check check (viewport is null or viewport in ('mobile', 'tablet', 'desktop'));
alter table public.feedback drop constraint if exists feedback_app_version_length_check;
alter table public.feedback add constraint feedback_app_version_length_check check (app_version is null or char_length(app_version) <= 40);

alter table public.feedback enable row level security;

drop policy if exists "Anyone can submit beta feedback" on public.feedback;
create policy "Anyone can submit beta feedback"
on public.feedback for insert
to anon, authenticated
with check (char_length(message) between 10 and 4000);

create index if not exists feedback_created_at_idx on public.feedback (created_at desc);
create index if not exists feedback_status_created_at_idx on public.feedback (status, created_at desc);
create index if not exists feedback_issue_type_created_at_idx on public.feedback (issue_type, created_at desc);

-- Privacy-minimized first-party product analytics. It stores random browser/session
-- identifiers and bounded product actions, never email addresses, passwords, full
-- URLs, IP addresses, or device fingerprints.
create table if not exists public.product_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in ('course_search', 'goal_route_requested', 'course_opened', 'resource_opened', 'favorite_added', 'favorite_removed', 'study_plan_created', 'study_task_completed', 'signup_completed')),
  anonymous_id uuid not null,
  session_id uuid not null,
  user_id uuid default auth.uid() references auth.users(id) on delete set null,
  course_id text check (course_id is null or char_length(course_id) <= 120),
  resource_type text check (resource_type is null or char_length(resource_type) <= 40),
  search_query text check (search_query is null or char_length(search_query) <= 160),
  numeric_value integer check (numeric_value is null or numeric_value between 0 and 3650),
  language text check (language is null or language in ('en', 'zh')),
  viewport text not null check (viewport in ('mobile', 'tablet', 'desktop')),
  page_path text not null check (char_length(page_path) between 1 and 500 and page_path not like '%?%'),
  created_at timestamptz not null default now()
);

alter table public.product_events enable row level security;

drop policy if exists "Visitors can submit anonymous product events" on public.product_events;
create policy "Visitors can submit anonymous product events"
on public.product_events for insert
to anon
with check (user_id is null);

drop policy if exists "Users can submit their own product events" on public.product_events;
create policy "Users can submit their own product events"
on public.product_events for insert
to authenticated
with check ((select auth.uid()) = user_id);

revoke all on table public.product_events from anon, authenticated;
grant insert on table public.product_events to anon, authenticated;
grant usage, select on sequence public.product_events_id_seq to anon, authenticated;

create index if not exists product_events_created_at_idx on public.product_events (created_at desc);
create index if not exists product_events_event_created_at_idx on public.product_events (event_name, created_at desc);
create index if not exists product_events_anonymous_created_at_idx on public.product_events (anonymous_id, created_at);
create index if not exists product_events_user_created_at_idx on public.product_events (user_id, created_at) where user_id is not null;
create index if not exists product_events_course_created_at_idx on public.product_events (course_id, created_at desc) where course_id is not null;

-- Open these owner-only views in Supabase Table Editor to inspect daily usage and
-- exact-day retention. No grants are given to website visitors.
create or replace view public.product_daily_summary
with (security_invoker = true)
as
select
  created_at::date as activity_date,
  event_name,
  count(*)::bigint as event_count,
  count(distinct anonymous_id)::bigint as visitor_count,
  count(distinct session_id)::bigint as session_count
from public.product_events
group by created_at::date, event_name;

create or replace view public.product_retention
with (security_invoker = true)
as
with visitor_days as (
  select distinct anonymous_id, created_at::date as activity_date
  from public.product_events
), cohorts as (
  select anonymous_id, min(activity_date) as cohort_date
  from visitor_days
  group by anonymous_id
)
select
  cohorts.cohort_date,
  count(*)::bigint as cohort_size,
  count(*) filter (where exists (select 1 from visitor_days where visitor_days.anonymous_id = cohorts.anonymous_id and visitor_days.activity_date = cohorts.cohort_date + 1))::bigint as day_1_returned,
  count(*) filter (where exists (select 1 from visitor_days where visitor_days.anonymous_id = cohorts.anonymous_id and visitor_days.activity_date = cohorts.cohort_date + 7))::bigint as day_7_returned,
  count(*) filter (where exists (select 1 from visitor_days where visitor_days.anonymous_id = cohorts.anonymous_id and visitor_days.activity_date = cohorts.cohort_date + 14))::bigint as day_14_returned,
  count(*) filter (where exists (select 1 from visitor_days where visitor_days.anonymous_id = cohorts.anonymous_id and visitor_days.activity_date = cohorts.cohort_date + 30))::bigint as day_30_returned
from cohorts
group by cohorts.cohort_date;

revoke all on table public.product_daily_summary from anon, authenticated;
revoke all on table public.product_retention from anon, authenticated;
