"use client";

import Link from "next/link";

type JourneyCourse = { id: string; code: string; title: string; href: string; percent: number; completed: number; total: number; paused: boolean };

export default function LearningJourney({ items, language }: { items: JourneyCourse[]; language: "en" | "zh" }) {
  if (items.length === 0) return <section className="mt-8 rounded-3xl border border-dashed border-violet-300 bg-violet-50 p-6"><p className="text-sm font-semibold text-violet-900">{language === "zh" ? "你的知识旅程还没有起点。" : "Your knowledge journey has not started yet."}</p><Link href={language === "zh" ? "/courses?lang=zh" : "/courses"} className="mt-3 inline-flex rounded-xl bg-violet-700 px-4 py-2.5 text-sm font-bold text-white">{language === "zh" ? "寻找第一门课程" : "Find your first course"} →</Link></section>;

  const unfinishedIndex = items.findIndex(({ percent, paused }) => percent < 100 && !paused);
  const currentIndex = unfinishedIndex >= 0 ? unfinishedIndex : items.length - 1;
  const current = items[currentIndex];
  const pathPercent = items.length === 1 ? current.percent : Math.min(100, ((currentIndex + current.percent / 100) / (items.length - 0.08)) * 100);

  return <section className="learning-journey mt-8 overflow-hidden rounded-3xl border border-violet-200 bg-gradient-to-br from-violet-50 via-blue-50 to-orange-50 p-5 sm:p-7">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="learning-journey-eyebrow text-xs font-bold uppercase tracking-[0.16em] text-violet-700">{language === "zh" ? "个人进度记录" : "Personal progress record"}</p><h2 className="learning-journey-title mt-1 text-2xl font-bold text-slate-950">{language === "zh" ? "我的学习足迹" : "My learning trail"}</h2><p className="learning-journey-copy mt-2 max-w-2xl text-sm text-slate-600">{language === "zh" ? "小人物停在你的真实位置；亮起的路线和圆点只代表你已经完成的课程任务。" : "The small explorer stands at your real position. Lit paths and dots represent only course tasks you have completed."}</p></div><Link href={language === "zh" ? "/today?lang=zh" : "/today"} className="learning-journey-action rounded-full bg-white px-4 py-2 text-sm font-bold text-violet-800 shadow-sm ring-1 ring-violet-200">{language === "zh" ? "继续今日学习" : "Continue today"} →</Link></div>
    <div className="mt-7 overflow-x-auto pb-3"><div className="relative min-w-[44rem] px-7 pt-12" style={{ width: `${Math.max(100, items.length * 24)}%` }}>
      <div className="absolute left-7 right-7 top-[4.35rem] h-1 rounded-full bg-white/90" /><div className="absolute left-7 top-[4.35rem] h-1 rounded-full bg-gradient-to-r from-violet-700 via-blue-600 to-orange-500 transition-[width] duration-700" style={{ width: `calc((100% - 3.5rem) * ${pathPercent / 100})` }} />
      <div className="absolute top-0 z-10 transition-[left] duration-700" style={{ left: `calc(1.75rem + (100% - 3.5rem) * ${pathPercent / 100})`, transform: "translateX(-50%)" }} aria-hidden="true"><div className="relative h-16 w-12"><div className="absolute left-4 top-0 h-5 w-5 rounded-full bg-slate-900" /><div className="absolute left-3 top-5 h-8 w-7 rounded-full bg-violet-700" /><div className="absolute left-2 top-11 h-7 w-2 origin-top rotate-[18deg] rounded-full bg-slate-900" /><div className="absolute right-2 top-11 h-7 w-2 origin-top -rotate-[18deg] rounded-full bg-slate-900" /></div></div>
      <ol className="relative grid gap-5" style={{ gridTemplateColumns: `repeat(${items.length}, minmax(10rem, 1fr))` }}>{items.map((item, index) => { const state = item.percent >= 100 ? "done" : index === currentIndex ? "current" : item.paused ? "paused" : "future"; const dotCount = Math.min(12, Math.max(3, item.total)); const litDots = Math.round(dotCount * item.percent / 100); return <li key={item.id} className="relative pt-12 text-center"><span className={`absolute left-1/2 top-[0.95rem] z-10 flex h-10 w-10 -translate-x-1/2 items-center justify-center rounded-full border-4 border-white text-sm font-black shadow-sm ${state === "done" ? "bg-emerald-600 text-white" : state === "current" ? "bg-violet-700 text-white" : state === "paused" ? "bg-amber-200 text-amber-950" : "bg-slate-200 text-slate-500"}`}>{state === "done" ? "✓" : index + 1}</span><Link href={item.href} className="learning-journey-course block rounded-2xl border border-white/80 bg-white/80 p-3 text-left shadow-sm backdrop-blur transition hover:-translate-y-0.5 hover:shadow-md"><span className="learning-journey-code text-xs font-bold text-violet-700">{item.code}</span><span className="learning-journey-course-title mt-1 line-clamp-2 block min-h-10 text-sm font-bold text-slate-950">{item.title}</span><span className="mt-3 flex items-center gap-1" aria-label={`${item.completed}/${item.total}`}>
        {Array.from({ length: dotCount }, (_, dot) => <span key={dot} className={`h-2 flex-1 rounded-full ${dot < litDots ? "bg-violet-600" : "bg-slate-200"}`} />)}
      </span><span className="mt-1 block text-xs text-slate-500">{item.paused ? (language === "zh" ? "已暂停" : "Paused") : `${item.completed}/${item.total} · ${item.percent}%`}</span></Link></li>; })}</ol>
    </div></div>
  </section>;
}
